### ISSUE TITLE
Uncaught (in promise) TypeError: Request method 'POST' is unsupported

### ISSUE THREAD

**Issue by nevson** [GoogleChrome/sw-toolbox#13]
Hi, when trying to run the Polymer Starter Kit I get following TypeError 

```
Uncaught (in promise) TypeError: Request method 'POST' is unsupported
    at TypeError (native)
    at http://localhost:3000/bower_components/sw-toolbox/sw-toolbox.js:20:430
```
I'm running `Chrome/43.0.2357.65`. Is this version of Chrome missing some features which are mandatory to use sw-toolbox?

**Comment by curtiscovington** [comment]
I'm having the exact same problem.

**Comment by addyosmani** [comment]
Should be fixed when we land https://github.com/GoogleChrome/sw-toolbox/pull/11

**Comment by wibblymat** [comment]
The patch landed and I bumped to v2.0.2. Should be fixed now.

**Comment by nevson** [comment]
Awesome, thanks :)!

**Comment by curtiscovington** [comment]
@wibblymat Just tested on v2.0.2, still getting the exact same errors.

**Comment by wibblymat** [comment]
@curtiscovington One possibility is that the old service worker is still active. You can force the worker to unregister by typing
`navigator.serviceWorker.getRegistration().then(function(r){r.unregister();});`
in the console, and then refresh the page.

**Comment by addyosmani** [comment]
@wibblymat thanks Mat!
@jeffposnick does platinum-sw need a bump for this?

**Comment by jeffposnick** [comment]
`<platinum-sw>` would pick it up for new installs, but I'll be explicit about requiring v2.0.2.

https://github.com/PolymerElements/platinum-sw/pull/36

**Comment by curtiscovington** [comment]
@wibblymat You got it, thanks!
